FEED_FORMAT = 'csv'

FEED_EXPORT_FIELDS = ['name', 'pieces', 'image']

FEED_URI = '/home/spacyk/Projects/data-catcher/lego.csv'

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 3
AUTOTHROTTLE_MAX_DELAY = 50
AUTOTHROTTLE_TARGET_CONCURRENCY = 1
AUTOTHROTTLE_DEBUG = False