FEED_FORMAT = 'csv'

FEED_EXPORT_FIELDS = ['name', 'webpage', 'email', 'phone', 'rating', 'ratings_number']

FEED_URI = '/home/spacyk/Projects/data-catcher/test.csv'

DOWNLOAD_DELAY = 1
AJAXCRAWL_ENABLED = True
COOKIES_ENABLED = False
RETRY_ENABLED = True

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 3
AUTOTHROTTLE_MAX_DELAY = 50
AUTOTHROTTLE_TARGET_CONCURRENCY = 1
AUTOTHROTTLE_DEBUG = False